apiVersion: apps/v1
kind: Deployment
metadata:
  name: fsapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fsapp
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: fsapp
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
        - name: fsapp
          image: aksregtcs.azurecr.io/fsapp:latest
          ports:
            - containerPort: 8080
              name: fsapp
---
apiVersion: v1
kind: Service
metadata:
  name: fsapp
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: fsapp
